version: "2.2"
services:
  pb_php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: "php"
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      # Application testing
      - ./../app:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    networks:
      dockernet:
        ipv4_address: 192.168.0.6

  pb_web:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=pb_php
    ports:
      - "8101:80"
    volumes:
      # Application testing
      - ./../app/web:/app/web:delegated
    networks:
      dockernet:
        ipv4_address: 192.168.0.5
    depends_on:
      - pb_php

  pb_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ilkinabd1
      MYSQL_DATABASE: pb
    networks:
      dockernet: 
        ipv4_address: 192.168.0.7

networks:
  dockernet:
    external: true
