version: "2.2"
services:
  php_b:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: "php"
      args:
        - PHP_BASE_IMAGE_VERSION
        - X_LEGACY_GD_LIB
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
    volumes:
      # Application testing
      - ./../app:/app:delegated
      - ~/.composer-docker/cache:/root/.composer/cache:delegated

  web_b:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - "8101:80"
    volumes:
      # Application testing
      - ./../app/web:/app/web:delegated
