version: '2.2'
services:
  web_b:
    image: phundament/nginx-one:1.9-5.1.1
    environment:
      - FASTCGI_PASS_HOST=php
    ports:
      - '8100:80'
    volumes:
      # Application testing
      - ./../app/web:/app/web:delegated
